// <auto-generated />
using System;
using DeskBookingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskBookingSystem.Data.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20241012070943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("DeskBookingSystem.Models.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Desks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            LocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = false,
                            LocationId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            LocationId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            LocationId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            LocationId = 3
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = false,
                            LocationId = 3
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = false,
                            LocationId = 4
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = false,
                            LocationId = 4
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = true,
                            LocationId = 5
                        });
                });

            modelBuilder.Entity("DeskBookingSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan.kowalski@mail.com",
                            IsAdmin = true,
                            Name = "Jan",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anna.kowalska@example.com",
                            IsAdmin = false,
                            Name = "Anna",
                            Surname = "Kowalska"
                        });
                });

            modelBuilder.Entity("DeskBookingSystem.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Biuro Główne - Kraków"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Biuro - Wrocław"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Biuro - Warszawa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biuro - Rzeszów"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Biuro - Bielsko-Biała"
                        });
                });

            modelBuilder.Entity("DeskBookingSystem.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HowManyDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeskId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2024, 10, 12, 9, 9, 43, 371, DateTimeKind.Local).AddTicks(3056),
                            DeskId = 1,
                            EmployeeId = 2,
                            HowManyDays = 2,
                            ReservationDate = new DateTime(2024, 10, 13, 9, 9, 43, 371, DateTimeKind.Local).AddTicks(3113)
                        });
                });

            modelBuilder.Entity("DeskBookingSystem.Models.Desk", b =>
                {
                    b.HasOne("DeskBookingSystem.Models.Location", "Location")
                        .WithMany("Desks")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DeskBookingSystem.Models.Reservation", b =>
                {
                    b.HasOne("DeskBookingSystem.Models.Desk", "Desk")
                        .WithMany("Reservations")
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeskBookingSystem.Models.Employee", "Employee")
                        .WithMany("Reservations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DeskBookingSystem.Models.Desk", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DeskBookingSystem.Models.Employee", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DeskBookingSystem.Models.Location", b =>
                {
                    b.Navigation("Desks");
                });
#pragma warning restore 612, 618
        }
    }
}
