global using Xunit;
global using DeskBookingSystem.Data;
global using Microsoft.EntityFrameworkCore;
global using DeskBookingSystem.Controllers;
global using Microsoft.AspNetCore.Mvc;
global using DeskBookingSystem.Repositories;
global using Moq;
global using DeskBookingSystem.Dto;
global using DeskBookingSystem.Services;